### ISSUE TITLE
src directory

### ISSUE THREAD

**Issue by anex004** [Kitware/DIVA#10]
As there is no src directory, should we create one and what should be the content of the directory?

**Comment by aaron-bray** [comment]
If you checked out the repo to a 'diva' directory containing all the files in your repository, then that is your 'src' directory and you can use that with cmake. Just be sure to make a build directory that is outside of your 'src' directory.

**Comment by anex004** [comment]
@aaron-bray: Thanks for getting back. Also, if I am using other repo as R-C3D (https://gitlab.kitware.com/kwiver/R-C3D), do I need to compile it along with the DIVA or a separate compilation of R-C3D works? Please let me know. Thanks in advance.

**Comment by aaron-bray** [comment]
You should compile DIVA first
That will create some libraries needed to build/run our R-C3D fork

**Comment by anex004** [comment]
Ok, got it. Will follow the steps. Thanks.

**Comment by kfieldho** [comment]
Closing this issue.
