### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by jlhbaseball15** [Kitware/DIVA#27]
Is it possible to build the python bindings so that they have both python 2 and 3 support? As of now, when I import the library from python 3, I get the following error:

```
ImportError: dynamic module does not define module export function (PyInit_diva_python_utils)
```
This is due to the bindings not being built with Python 3 support. Is it possible to change the configuration to build for Python 3 or preferably, both?

More importantly, Python 3 support is a must as Python 2 is EOL starting in 2020.

**Comment by TaeSoo-Kim** [comment]
I second this, is there an update on this?

**Comment by as6520** [comment]
#29 allows you to choose python major version and uses python3 as default. As for targeting multiple python version maybe something like https://github.com/pybind/pybind11/issues/748 is possible.

**Comment by kfieldho** [comment]
With Python 3 support integrated, closing this issue.
