### ISSUE TITLE
Extendability for new types for the Sprokit pipeline

### ISSUE THREAD

**Issue by jlhbaseball15** [Kitware/DIVA#34]
Currently, there doesn't seem to be a good way to add more types to the Sprokit pipeline. The example pipelines use single components (ACT, R-C3D) to do activity detection, and the provided types are enough for those components. However, many systems built by DIVA participants have more components than just an activity detector and need to be able to define custom types for these components. 

I think there should be an API for defining and registering new data types similar to how there is an API for registering components with Sprokit.

**Comment by as6520** [comment]
In the global context:
You can define a new data type in [vital](https://github.com/Kitware/kwiver/tree/master/vital/types) and register it [here](https://github.com/Kitware/kwiver/blob/5653657271ef1de97d66d1ea17e1c239303b56fd/sprokit/processes/kwiver_type_traits.h).

In application specific context:
Once you have defined your application specific data types, you can create a new header (similar to kwiver_type_traits.h), register the types in that header and include it in your processes. An example is present [here](https://github.com/Kitware/kwiver/blob/0103c709c7ca28db847635972c8067a5671d7e05/sprokit/processes/examples/process_template/template_type_traits.h).

**Comment by jlhbaseball15** [comment]
Is there a way to register them using python?

**Comment by as6520** [comment]
To clarify, the data type is written in python not in c++ right ?

**Comment by jlhbaseball15** [comment]
yes

**Comment by as6520** [comment]
There is way to do it. I have not used it yet and I am not aware of an example where this functionality is demonstrated. 

Sprokit wraps the data that is being sent across pipeline in datum and provides methods to access the datum. You can create a datum of the data that you want to push using the function [new](https://github.com/Kitware/kwiver/blob/0103c709c7ca28db847635972c8067a5671d7e05/sprokit/src/bindings/python/sprokit/pipeline/datum.cxx#L94) and push it to a port using [push_datum_to_port_using_trait](https://github.com/Kitware/kwiver/blob/0103c709c7ca28db847635972c8067a5671d7e05/sprokit/processes/bindings/python/kwiver/kwiver_process.py#L394). On the receiving process, using [grab_datum_from_port](https://github.com/Kitware/kwiver/blob/0103c709c7ca28db847635972c8067a5671d7e05/sprokit/processes/bindings/python/kwiver/kwiver_process.py#L312) to grab the datum from the port and use [get_datum](https://github.com/Kitware/kwiver/blob/0103c709c7ca28db847635972c8067a5671d7e05/sprokit/src/bindings/python/sprokit/pipeline/datum.cxx#L146) to get the data back.

I can look into it and get back to you with a more concrete example as there might be some subtleties I might have missed which might cause things to not work. But essentially this would be the way to do it.

**Comment by as6520** [comment]
The [repo](https://github.com/as6520/pipe-without-vital) demonstrates this functionality. It was slightly easier that I had anticipated as you can define a new type trait in the process that you want to communicate and just send them across the pipeline using this new trait.

**Comment by jlhbaseball15** [comment]
So you pass the type's class name as a string?

**Comment by as6520** [comment]
Not necessarily. The function signatures are available [here](https://github.com/Kitware/kwiver/blob/0103c709c7ca28db847635972c8067a5671d7e05/sprokit/processes/bindings/python/kwiver/kwiver_process.py) with docstring comments on type and port traits. When you add a type trait, you are specifying the name of the type trait and the canonical name of the type trait. Sprokit matches the canonical name to connect ports in the pipeline not the type name. You can create namespaces in the canonical name as show [here](https://github.com/Kitware/kwiver/blob/0103c709c7ca28db847635972c8067a5671d7e05/sprokit/processes/bindings/python/kwiver/kwiver_process.py#L150) using ":" operator. 

When a port trait is added, we use the type name not the canonical type name as the second argument. This allows different port name with the same type to be added without creating ambiguity.

**Comment by as6520** [comment]
Closing this issue as it appears to be solved. Feel free to open it if there are any more questions.
