### ISSUE TITLE
Orphan tracks created by eo-to-ir.py

### ISSUE THREAD

**Issue by kelliecorona** [Kitware/DIVA#44]
@dmjoy The eo-to-ir python script appears to be creating tracks that do not have associated events in the IR annotations. I have not yet had a chance to dig into this further.

**Comment by dmjoy** [comment]
Hi Kellie, that's strange.  Would you be able to share some input files (out of band) where this is happening and I can take a look?

**Comment by kelliecorona** [comment]
HI David, of course. Emailing you now.

**Comment by dmjoy** [comment]
I believe this issue has been fixed with #45 ; if you can confirm, I'll merge the changes and close the issue.  Thanks!

**Comment by kelliecorona** [comment]
Confirmed. Apologies for the delay and thank you for helping me with this. Thanks!

**Comment by dmjoy** [comment]
No problem!  Closing the issue and merging in the changes.
