### ISSUE TITLE
"Super build" fails in opencv_waldboost_detector

### ISSUE THREAD

**Issue by taa01776** [Kitware/DIVA#6]
Using entirely defaulted settings, builds from the top level of the DIVA repo failed with undefined symbols in opencv_waldboost_detector; it couldn't find libswresample.so from FFmpeg (which is built earlier in the process). I found that adding ${CMAKE_INSTALL_PREFIX}/lib to LD_LIBRARY_PATH before building solved the problem, but that seems sub-optimal, and should at least be documented.

**Comment by aaron-bray** [comment]
What operating system are you building on?

**Comment by taa01776** [comment]
CentOS 7, just updated.
                -ta

**Comment by aaron-bray** [comment]
As a temporary work around, you can do this from your build directory

$ export LD_LIBRARY_PATH=${PWD}/install/lib
Then make the project again
$ make

I will put in a fix so this builds correctly without the need for setting this environment variable

**Comment by taa01776** [comment]
Yeah, that’s what I did. A little tedious, but not a problem once I figured it out.
                -ta

**Comment by aaron-bray** [comment]
A Fletch Fix was pushed and DIVA now pulls a version of Fletch with that fix
